
# tap repositories and their packages

tap 'homebrew/core'
brew 'autoconf'
brew 'cairo'
brew 'docker'
brew 'fontconfig'
brew 'fontforge'
brew 'freetype'
brew 'gdbm'
brew 'gettext'
brew 'ghq'
brew 'git'
brew 'glib'
brew 'gobject-introspection'
brew 'graphite2'
brew 'harfbuzz'
brew 'haskell-stack'
brew 'icu4c'
brew 'jenv'
brew 'jpeg'
brew 'libffi'
brew 'libpng'
brew 'libtiff'
brew 'libtool'
brew 'mas'
brew 'maven'
brew 'openssl'
brew 'pango'
brew 'pcre'
brew 'peco'
brew 'pixman'
brew 'pkg-config'
brew 'postgresql'
brew 'pyenv'
brew 'readline'
brew 'tomcat'
brew 'tree'
brew 'zplug'
brew 'zsh'

tap 'caskroom/cask'
cask 'rstudio'
cask 'slack'
cask 'flux'
cask 'r-app'
cask 'eclipse-java'
cask 'macvim'
cask 'skype'
cask 'appcleaner'
cask 'cmd-eikana'
cask 'onedrive'
cask 'macdown'
cask 'evernote'
cask 'iterm2'
cask 'dropbox'
cask 'enpass'
cask 'docker'
cask 'clipy'
cask 'caffeine'
cask 'gfxcardstatus'
cask 'sublime-text'
cask 'android-studio'
cask 'night-owl'
cask 'firefox'
cask 'boostnote'
cask 'google-chrome'
cask 'xquartz'
cask 'google-japanese-ime'
cask 'java'
cask 'plain-clip'
cask 'sourcetree'
cask 'opera'
cask 'alfred'
cask 'skitch'

tap 'caskroom/fonts'
cask 'font-hack-nerd-font'

tap 'caskroom/versions'
cask 'java8'

tap 'rcmdnk/file'
brew 'brew-file'

tap 'sanemat/font'
brew 'ricty'
